export interface ColorCustomization {

    // Contrast Colors - The contrast colors are typically only set for high contrast themes. If set, they add an additional border around items across the UI to increase the contrast.
    "contrastActiveBorder"?: string,
    "contrastBorder"?: string,
    // Base Colors
    "focusBorder"?: string,
    "foreground"?: string,
    "widget.shadow"?: string,
    "selection.background"?: string,
    "descriptionForeground"?: string,
    "errorForeground"?: string,
    // Text Colors — Colors inside a text document, such as the welcome page.
    "textBlockQuote.background"?: string,
    "textBlockQuote.border"?: string,
    "textCodeBlock.background"?: string,
    "textLink.activeForeground"?: string,
    "textLink.foreground"?: string,
    "textPreformat.foreground"?: string,
    "textSeparator.foreground"?: string,
    // Button Control — A set of colors for button widgets such as Open Folder button in the Explorer of a new window.
    "button.background"?: string,
    "button.foreground"?: string,
    "button.hoverBackground"?: string,
    // Dropdown Control — A set of colors for all dropdown widgets such as in the Integrated Terminal or the Output panel. Note that the dropdown control is not used on macOS currently.
    "dropdown.background"?: string,
    "dropdown.listBackground"?: string,
    "dropdown.border"?: string,
    "dropdown.foreground"?: string,
    // Input Control — Colors for input controls such as in the Search view or the Find/Replace dialog.
    "input.background"?: string,
    "input.border"?: string,
    "input.foreground"?: string,
    "input.placeholderForeground"?: string,
    "inputOption.activeBorder"?: string,
    "inputValidation.errorBackground"?: string,
    "inputValidation.errorBorder"?: string,
    "inputValidation.infoBackground"?: string,
    "inputValidation.infoBorder"?: string,
    "inputValidation.warningBackground"?: string,
    "inputValidation.warningBorder"?: string,
    // Scroll Bar Control
    "scrollbar.shadow"?: string,
    "scrollbarSlider.activeBackground"?: string,
    "scrollbarSlider.background"?: string,
    "scrollbarSlider.hoverBackground"?: string,
    // Badge — Badges are small information labels, for example, search results count.
    "badge.foreground"?: string,
    "badge.background"?: string,
    // Progress Bar
    "progressBar.background"?: string,
    // Lists and Trees — Colors for list and trees like the File Explorer. An active list/tree has keyboard focus, an inactive does not.
    "list.activeSelectionBackground"?: string,
    "list.activeSelectionForeground"?: string,
    "list.dropBackground"?: string,
    "list.focusBackground"?: string,
    "list.focusForeground"?: string,
    "list.highlightForeground"?: string,
    "list.hoverBackground"?: string,
    "list.hoverForeground"?: string,
    "list.inactiveSelectionBackground"?: string,
    "list.inactiveSelectionForeground"?: string,
    "list.inactiveFocusBackground"?: string,
    "list.invalidItemForeground"?: string,
    // Activity Bar — The Activity Bar is displayed either on the far left or right of the workbench and allows fast switching between views of the Side Bar.
    "activityBar.background"?: string,
    "activityBar.dropBackground"?: string,
    "activityBar.foreground"?: string,
    "activityBar.activeBorder"?: string,
    "activityBar.border"?: string,
    "activityBarBadge.background"?: string,
    "activityBarBadge.foreground"?: string,
    "activityBar.inactiveForeground"?: string,
    // Side Bar — The Side Bar contains views like the Explorer and Search.
    "sideBar.background"?: string,
    "sideBar.foreground"?: string,
    "sideBar.border"?: string,
    "sideBar.dropBackground"?: string,
    "sideBarTitle.foreground"?: string,
    "sideBarSectionHeader.background"?: string,
    "sideBarSectionHeader.foreground"?: string,
    // Editor Groups & Tabs — Editor Groups are the containers of editors. There can be up to three editor groups. A Tab is the container of an editor. Multiple Tabs can be opened in one editor group.
    "editorGroup.background"?: string,
    "editorGroup.border"?: string,
    "editorGroup.dropBackground"?: string,
    "editorGroupHeader.noTabsBackground"?: string,
    "editorGroupHeader.tabsBackground"?: string,
    "editorGroupHeader.tabsBorder"?: string,
    "tab.activeBackground"?: string,
    "tab.activeForeground"?: string,
    "tab.border"?: string,
    "tab.activeBorder"?: string,
    "tab.unfocusedActiveBorder"?: string,
    "tab.inactiveBackground"?: string,
    "tab.inactiveForeground"?: string,
    "tab.unfocusedActiveForeground"?: string,
    "tab.unfocusedInactiveForeground"?: string,
    "tab.hoverBackground"?: string,
    "tab.unfocusedHoverBackground"?: string,
    "tab.hoverBorder"?: string,
    "tab.unfocusedHoverBorder"?: string,
    // Editor Colors — for syntax highlighting, use the editor.tokenColorCustomizations setting. All other editor colors are listed here
    "editor.background"?: string,
    "editor.foreground"?: string,
    "editorLineNumber.foreground"?: string,
    "editorLineNumber.activeForeground"?: string,
    "editorCursor.background"?: string,
    "editorCursor.foreground"?: string,
    "editor.selectionBackground"?: string,
    "editor.selectionForeground"?: string,
    "editor.inactiveSelectionBackground"?: string,
    "editor.selectionHighlightBackground"?: string,
    "editor.selectionHighlightBorder"?: string,
    "editor.wordHighlightBackground"?: string,
    "editor.wordHighlightBorder"?: string,
    "editor.worldHighlightStrongBackground"?: string,
    "editor.wordHighlightStrongBorder"?: string,
    "editor.findMatchBackground"?: string,
    "editor.findMatchHighlightBackground"?: string,
    "editor.findRangeHighlightBackground"?: string,
    "editor.findMatchBorder"?: string,
    "editor.findMatchHighlightBorder"?: string,
    "editor.hoverHighlightBackground"?: string,
    "editor.lineHighlightBackground"?: string,
    "editor.lineHighlightBorder"?: string,
    "editorLink.activeForeground"?: string,
    "editor.rangeHighlightBackground"?: string,
    "editor.rangeHighlightBorder"?: string,
    "editorWhitespace.foreground"?: string,
    "editorIndentGuide.background"?: string,
    "editorRuler.foreground"?: string,
    "editorCodeLens.foreground"?: string,
    "editorBracketMatch.background"?: string,
    "editorBracketMatch.border"?: string,
    "editorOverviewRuler.border"?: string,
    "editorOverviewRuler.findMatchForeground"?: string,
    "editorOverviewRuler.rangeHighlightForeground"?: string,
    "editorOverviewRuler.selectionHighlightForeground"?: string,
    "editorOverviewRuler.wordHighlightForeground"?: string,
    "editorOverviewRuler.wordHighlightStrongForeground"?: string,
    "editorOverviewRuler.modifiedForeground"?: string,
    "editorOverviewRuler.addedForeground"?: string,
    "editorOverviewRuler.deletedForeground"?: string,
    "editorOverviewRuler.errorForeground"?: string,
    "editorOverviewRuler.warningForeground"?: string,
    "editorOverviewRuler.infoForeground"?: string,
    "editorError.foreground"?: string,
    "editorError.border"?: string,
    "editorWarning.foreground"?: string,
    "editorWarning.border"?: string,
    "editorInfo.foreground"?: string,
    "editorInfo.border"?: string,
    "editorHint.foreground"?: string,
    "editorHint.border"?: string,
    "editorGutter.background"?: string,
    "editorGutter.modifiedBackground"?: string,
    "editorGutter.addedBackground"?: string,
    "editorGutter.deletedBackground"?: string,
    // Diff Editor Colors — For coloring inserted and removed text, use either a background or a border color but not both.
    "diffEditor.insertedTextBackground"?: string,
    "diffEditor.insertedTextBorder"?: string,
    "diffEditor.removedTextBackground"?: string,
    "diffEditor.removedTextBorder"?: string,
    // Editor Widget Colors - The Editor widget is shown in front of the editor content. Examples are the Find/Replace dialog, the suggestion widget, and the editor hover
    "editorWidget.background"?: string,
    "editorWidget.border"?: string,
    "editorSuggestWidget.background"?: string,
    "editorSuggestWidget.border"?: string,
    "editorSuggestWidget.foreground"?: string,
    "editorSuggestWidget.highlightForeground"?: string,
    "editorSuggestWidget.selectedBackground"?: string,
    "editorHoverWidget.background"?: string,
    "editorHoverWidget.border"?: string,
    "debugExceptionWidget.background"?: string,
    "debugExceptionWidget.border"?: string,
    "editorMarkerNavigation.background"?: string,
    "editorMarkerNavigationError.background"?: string,
    "editorMarkerNavigationWarning.background"?: string,
    "editorMarkerNavigationInfo.background"?: string,
    // Peek View Colors — Peek views are used to show references and declarations as a view inside the editor.
    "peekView.border"?: string,
    "peekViewEditor.background"?: string,
    "peekViewEditorGutter.background"?: string,
    "peekViewEditor.matchHighlightBackground"?: string,
    "peekViewResult.background"?: string,
    "peekViewResult.fileForeground"?: string,
    "peekViewResult.lineForeground"?: string,
    "peekViewResult.matchHighlightBackground"?: string,
    "peekViewResult.selectionBackground"?: string,
    "peekViewResult.selectionForeground"?: string,
    "peekViewTitle.background"?: string,
    "peekViewTitleDescription.foreground"?: string,
    "peekViewTitleLabel.foreground"?: string,
    // Merge Conflicts — Merge conflict decorations are shown when the editor contains special diff ranges.
    "merge.currentHeaderBackground"?: string,
    "merge.currentContentBackground"?: string,
    "merge.incomingHeaderBackground"?: string,
    "merge.incomingContentBackground"?: string,
    "merge.border"?: string,
    "merge.commonContentBackground"?: string,
    "merge.commonHeaderBackground"?: string,
    "editorOverviewRuler.currentContentForeground"?: string,
    
    "editorOverviewRuler.commonContentForeground"?: string,
    // Panel Colors — Panels are shown below the editor area and contain views like Output and Integrated Terminal.
    "panel.background"?: string,
    "panel.border"?: string,
    "panel.dropBackground"?: string,
    "panelTitle.activeBorder"?: string,
    "panelTitle.activeForeground"?: string,
    "panelTitle.inactiveForeground"?: string,
    // Status Bar Colors — The Status Bar is shown in the bottom of the workbench.
    "statusBar.background"?: string,
    "statusBar.foreground"?: string,
    "statusBar.border"?: string,
    "statusBar.debuggingBackground"?: string,
    "statusBar.debuggingForeground"?: string,
    "statusBar.debuggingBorder"?: string,
    "statusBar.noFolderForeground"?: string,
    "statusBar.noFolderBackground"?: string,
    "statusBar.noFolderBorder"?: string,
    "statusBarItem.activeBackground"?: string,
    "statusBarItem.hoverBackground"?: string,
    "statusBarItem.prominentBackground"?: string,
    "statusBarItem.prominentHoverBackground"?: string,
    "statusBarItem.remoteBackground"?: string,
    "statusBarItem.remoteForeground"?: string,
    // Title Bar Colors (macOS)
    "titleBar.activeBackground"?: string,
    "titleBar.activeForeground"?: string,
    "titleBar.inactiveBackground"?: string,
    "titleBar.inactiveForeground"?: string,
    "titleBar.border"?: string,
    // Notification Colors — Notification toasts slide up from the bottom-right of the workbench.
    "notificationCenter.border"?: string,
    "notificationCenterHeader.foreground"?: string,
    "notificationCenterHeader.background"?: string,
    "notificationToast.border"?: string,
    "notifications.foreground"?: string,
    "notifications.background"?: string,
    "notifications.border"?: string,
    "notificationLink.foreground"?: string,
    // Extensions
    "extensionButton.prominentForeground"?: string,
    "extensionButton.prominentBackground"?: string,
    "extensionButton.prominentHoverBackground"?: string,
    "pickerGroup.border"?: string,
    "pickerGroup.foreground"?: string,
    // Integrated Terminal Colors
    "terminal.background"?: string,
    "terminal.foreground"?: string,
    "terminal.ansiBlack"?: string,
    "terminal.ansiBlue"?: string,
    "terminal.ansiBrightBlack"?: string,
    "terminal.ansiBrightBlue"?: string,
    "terminal.ansiBrightCyan"?: string,
    "terminal.ansiBrightGreen"?: string,
    "terminal.ansiBrightMagenta"?: string,
    "terminal.ansiBrightRed"?: string,
    "terminal.ansiBrightWhite"?: string,
    "terminal.ansiBrightYellow"?: string,
    "terminal.ansiCyan"?: string,
    "terminal.ansiGreen"?: string,
    "terminal.ansiMagenta"?: string,
    "terminal.ansiRed"?: string,
    "terminal.ansiWhite"?: string,
    "terminal.ansiYellow"?: string,
    "terminal.selectionBackground"?: string,
    "terminalCursor.background"?: string,
    "terminalCursor.foreground"?: string,
    // Debug
    "debugToolBar.background"?: string,
    // Welcome Page
    "welcomePage.buttonBackground"?: string,
    "welcomePage.buttonHoverBackground"?: string,
    "walkThrough.embeddedEditorBackground"?: string,
    // Git Colors
    "gitDecoration.modifiedResourceForeground"?: string,
    "gitDecoration.deletedResourceForeground"?: string,
    "gitDecoration.untrackedResourceForeground"?: string,
    "gitDecoration.ignoredResourceForeground"?: string,
    "gitDecoration.conflictingResourceForeground"?: string

}
